[FEATURE] Config file as argument
anna-singleton/runfast pull request #18
Opened 2022-11-03 16:05 UTC by leon3s

Hey there i did couple of modification !

- Added a build.rs file to generate man page of your program using `clap_mangen`
- Updated your main cause you seems not really liked it
- Refactor the `preview` function to use `format!`
- Couple of bugfix if chosen runner is empty
- Added an option to choose a specific config file to load

2022-11-03 16:33 UTC, leon3s commented
Your welcome,
You can ping me on discord if you wanna discuss about my choices.
Also if you need help to setup your CI i'll be happy to share my knowledge!

2022-11-04 09:04 UTC, anna-singleton commented
Hi, I forgot to add how I want the branches to work when I made this repo (honestly wasnt expecting any PRs yet). Could you please merge with the `dev` branch instead of `main`. My reasoning for this is now in the `readme.md` file on `main`.

thanks again

2022-11-04 18:19 UTC, anna-singleton requested changes
Ive left a few suggestions, theyre mostly little things, including a couple suggestions straight from the `cargo clippy` tool. If you make these changes i'm happy to merge.

2022-11-04 18:19 UTC, anna-singleton commented on src/cli.rs
> +    #[arg(short, long="config-path", help="Load specific toml config", default_value="~/.config/runfast/runners.toml")]
i would prefer this to be called `runners-path` instead of `config-path` since I can envision having a separate config file in the future.

2022-11-04 18:19 UTC, anna-singleton commented on src/main.rs
> +fn select_new_runner(
nit: please put this all on one line, its not long enough to be separated like this in my opinion

2022-11-04 18:19 UTC, anna-singleton commented on src/main.rs
> +                std::process::exit(1);
This is not a behavior I want. It should still be possible to select a runner, without writing the cache if it is corrupted. This is what the normal (no force choose new) version does.

2022-11-04 18:19 UTC, anna-singleton commented on src/main.rs
> +    if result.final_event == Event::EvActAbort || result.selected_items.len() == 0 {
clippy suggestion:
```
warning: length comparison to zero
   --> src/main.rs:120:51
    |
120 |     if result.final_event == Event::EvActAbort || result.selected_items.len() == 0 {
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: using `is_empty` is clearer and more explicit: `result.selected_items.is_empty()`
    |
    = note: `#[warn(clippy::len_zero)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
```

2022-11-04 18:19 UTC, anna-singleton commented on src/main.rs
> +                    cache.add_runner(&runner.as_ref().unwrap());
clippy suggestion:
```
warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/main.rs:150:38
    |
150 |                     cache.add_runner(&runner.as_ref().unwrap());
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `runner.as_ref().unwrap()`
    |
    = note: `#[warn(clippy::needless_borrow)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```

2022-11-04 18:19 UTC, anna-singleton commented on src/main.rs
> +                        cache.add_runner(&runner.as_ref().unwrap());
clippy suggestion:
```
warning: this expression creates a reference which is immediately dereferenced by the compiler
   --> src/main.rs:166:42
    |
166 |                         cache.add_runner(&runner.as_ref().unwrap());
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `runner.as_ref().unwrap()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```

2022-11-04 21:00 UTC, anna-singleton approved these changes
lgtm, great work

2022-11-04 21:02 UTC, merged